// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Accounts    string
	Articles    string
	Comments    string
	Contacts    string
	Photographs string
}{
	Accounts:    "accounts",
	Articles:    "articles",
	Comments:    "comments",
	Contacts:    "contacts",
	Photographs: "photographs",
}
